#ifndef ANALISADOR_SINTATICO_H
#define ANALISADOR_SINTATICO_H

#include <stdbool.h>
#include "../Analisador Lexico/analisador_lexico.h"

// FIRST sets
#define FIRST_programa { TOKEN_INICIO }
#define FIRST_decls { TOKEN_TIPO_INT, TOKEN_TIPO_FLOAT, TOKEN_TIPO_STRING}
#define FIRST_decl { TOKEN_TIPO_INT, TOKEN_TIPO_FLOAT, TOKEN_TIPO_STRING }
#define FIRST_tipo { TOKEN_TIPO_INT, TOKEN_TIPO_FLOAT, TOKEN_TIPO_STRING }
#define FIRST_comandos { TOKEN_IDENTIFICADOR, TOKEN_READ, TOKEN_PRINT, TOKEN_IF, TOKEN_WHILE, TOKEN_ABRE_CHAVES}
#define FIRST_comando { TOKEN_IDENTIFICADOR, TOKEN_READ, TOKEN_PRINT, TOKEN_IF, TOKEN_WHILE, TOKEN_ABRE_CHAVES }
#define FIRST_atribuicao { TOKEN_IDENTIFICADOR }
#define FIRST_chamada { TOKEN_IDENTIFICADOR }
#define FIRST_args { TOKEN_IDENTIFICADOR, TOKEN_NUMERO, TOKEN_STRING, TOKEN_ABRE_PARENTESES, TOKEN_OPERADOR_SUB}
#define FIRST_expr_list { TOKEN_IDENTIFICADOR, TOKEN_NUMERO, TOKEN_STRING, TOKEN_ABRE_PARENTESES, TOKEN_OPERADOR_SUB }
#define FIRST_entrada { TOKEN_READ }
#define FIRST_saida { TOKEN_PRINT }
#define FIRST_if_stmt { TOKEN_IF }
#define FIRST_else_opt { TOKEN_ELSE}
#define FIRST_while_stmt { TOKEN_WHILE }
#define FIRST_bloco { TOKEN_ABRE_CHAVES }
#define FIRST_factor { TOKEN_IDENTIFICADOR, TOKEN_NUMERO, TOKEN_STRING, TOKEN_ABRE_PARENTESES, TOKEN_OPERADOR_SUB }
#define FIRST_expr { TOKEN_IDENTIFICADOR, TOKEN_NUMERO, TOKEN_STRING, TOKEN_ABRE_PARENTESES, TOKEN_OPERADOR_SUB }
#define FIRST_expr_linha { TOKEN_OPERADOR_SOMA, TOKEN_OPERADOR_SUB}
#define FIRST_term { TOKEN_IDENTIFICADOR, TOKEN_NUMERO, TOKEN_STRING, TOKEN_ABRE_PARENTESES, TOKEN_OPERADOR_SUB }
#define FIRST_term_linha { TOKEN_OPERADOR_MUL, TOKEN_OPERADOR_DIV}

// FOLLOW sets
#define FOLLOW_programa { TOKEN_EOF }
#define FOLLOW_decls { TOKEN_IDENTIFICADOR, TOKEN_READ, TOKEN_PRINT, TOKEN_IF, TOKEN_WHILE, TOKEN_ABRE_CHAVES, TOKEN_FIM }
#define FOLLOW_decl { TOKEN_TIPO_INT, TOKEN_TIPO_FLOAT, TOKEN_TIPO_STRING, TOKEN_IDENTIFICADOR, TOKEN_READ, TOKEN_PRINT, TOKEN_IF, TOKEN_WHILE, TOKEN_ABRE_CHAVES, TOKEN_FIM }
#define FOLLOW_tipo { TOKEN_IDENTIFICADOR }
#define FOLLOW_comandos { TOKEN_FIM, TOKEN_FECHA_CHAVES }
#define FOLLOW_comando { TOKEN_IDENTIFICADOR, TOKEN_READ, TOKEN_PRINT, TOKEN_IF, TOKEN_WHILE, TOKEN_ABRE_CHAVES, TOKEN_FIM, TOKEN_FECHA_CHAVES }
#define FOLLOW_atribuicao { TOKEN_PONTO_VIRGULA }
#define FOLLOW_chamada { TOKEN_PONTO_VIRGULA }
#define FOLLOW_args { TOKEN_FECHA_PARENTESES }
#define FOLLOW_expr_list { TOKEN_FECHA_PARENTESES }
#define FOLLOW_entrada { TOKEN_PONTO_VIRGULA }
#define FOLLOW_saida { TOKEN_PONTO_VIRGULA }
#define FOLLOW_if_stmt { TOKEN_IDENTIFICADOR, TOKEN_READ, TOKEN_PRINT, TOKEN_IF, TOKEN_WHILE, TOKEN_ABRE_CHAVES, TOKEN_FIM, TOKEN_FECHA_CHAVES }
#define FOLLOW_else_opt { TOKEN_IDENTIFICADOR, TOKEN_READ, TOKEN_PRINT, TOKEN_IF, TOKEN_WHILE, TOKEN_ABRE_CHAVES, TOKEN_FIM, TOKEN_FECHA_CHAVES }
#define FOLLOW_while_stmt { TOKEN_IDENTIFICADOR, TOKEN_READ, TOKEN_PRINT, TOKEN_IF, TOKEN_WHILE, TOKEN_ABRE_CHAVES, TOKEN_FIM, TOKEN_FECHA_CHAVES }
#define FOLLOW_bloco { TOKEN_IDENTIFICADOR, TOKEN_READ, TOKEN_PRINT, TOKEN_IF, TOKEN_WHILE, TOKEN_ABRE_CHAVES, TOKEN_FIM, TOKEN_FECHA_CHAVES }
#define FOLLOW_factor { TOKEN_OPERADOR_SOMA, TOKEN_OPERADOR_SUB, TOKEN_OPERADOR_MUL, TOKEN_OPERADOR_DIV, TOKEN_VIRGULA, TOKEN_FECHA_PARENTESES, TOKEN_PONTO_VIRGULA }
#define FOLLOW_expr { TOKEN_FECHA_PARENTESES, TOKEN_VIRGULA, TOKEN_PONTO_VIRGULA }
#define FOLLOW_expr_linha { TOKEN_FECHA_PARENTESES, TOKEN_VIRGULA, TOKEN_PONTO_VIRGULA }
#define FOLLOW_term { TOKEN_OPERADOR_SOMA, TOKEN_OPERADOR_SUB, TOKEN_FECHA_PARENTESES, TOKEN_VIRGULA, TOKEN_PONTO_VIRGULA }
#define FOLLOW_term_linha { TOKEN_OPERADOR_SOMA, TOKEN_OPERADOR_SUB, TOKEN_FECHA_PARENTESES, TOKEN_VIRGULA, TOKEN_PONTO_VIRGULA }


bool analisar(const char* codigo_fonte);

#endif